name: Deploy to VPS

on:
  push:
    branches: [ main ]
  workflow_dispatch: # Allow manual triggering from GitHub UI

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            # IMPORTANT: Update this path to match your subdomain
            # For subdomain.benlamb.net, use /var/www/subdomain.benlamb.net
            cd /var/www/jeopardy.benlamb.net || exit 1
            
            # Pull latest changes
            echo "Pulling latest changes from GitHub..."
            git pull origin main || git pull origin master
            
            # Set proper permissions for web files
            echo "Setting file permissions..."
            find . -type f \( -name "*.html" -o -name "*.js" -o -name "*.css" -o -name "*.json" \) -exec chmod 644 {} \;
            find . -type d -exec chmod 755 {} \;
            
            # Optional: Run build commands if needed
            # npm install --production
            # npm run build
            
            # Output success message
            echo "Deployment completed successfully at $(date)"
            echo "Site is now live at https://jeopardy.benlamb.net"
