name: Auto-generate files.json

on:
  push:
    branches: [ main ]
    paths: [ 'data/**/*.json' ]
  pull_request:
    branches: [ main ]
    paths: [ 'data/**/*.json' ]
  workflow_dispatch: # Allow manual trigger

# Minimal permissions for security
permissions:
  contents: write

jobs:
  update-files-index:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: Generate files.json
      run: node generate-files-index.js
    
    - name: Check for changes
      id: verify-changed-files
      run: |
        if git diff --quiet data/files.json; then
          echo "changed=false" >> $GITHUB_OUTPUT
        else
          echo "changed=true" >> $GITHUB_OUTPUT
        fi
    
    - name: Commit and push changes
      if: steps.verify-changed-files.outputs.changed == 'true' && github.event_name == 'push'
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add data/files.json
        git commit -m "Auto-update files.json index [skip ci]"
        git push
    
    - name: Display results
      run: |
        echo "Files index updated successfully!"
        echo "Current files.json content:"
        cat data/files.json
